sudo: required
language: minimal
services:
- docker
script: "./ci/publish_docker.sh"
branches:
  except:
  - gh-pages
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: W/zk86TB17ioOi1T2yDfmpEth24tOuWUWOt28KOEoiItPO+fLw9eT4+4DSrREVMptf4RxUMmSeOOQJRwYD2jzk5VyV/Bw7pZzMxaXKmrGxduEhXQAZ3zbPfe2NkcS/7TQb9Qx97vpWQbgx9f+tNPdRbtclVzBZCae6etwiS7mZAIwIIZf/qSoxf04Dwmn2yY3DkR3PVUwa2fjzjCNAV4crdpzTfJhZicDLKEybjGgo/F0iAoEZiNFrL0qlxAX1gbtXLyHiVuCnW/ihs2k8Fw2SLuoZly2i+lz0lfZ/vKXP6/V5qV1R96VWcen4Y8Bq0UBm/fVmcYTJBNfm4wWHD5lr1JYyQwTzORVyPVJRE0NDRFB/fjqCDUMNacss/P5YLSnBbHw3TnM9aXeQima2G6kOu8DHgxC0SCkXazT3PDWzhVwyxKBknUx5wayrnrOoGhGOP2EUUe5wKWAoKVTx1FL3XCf3Ji33fSfw+fWXJ9A4WlMyErRiNCvyuh16PJbLfDJ5Jb2Qn6Pl4CjRxSf8NEt9Q/ZFTNhfiOZl3xp530Lat0Ct/X+Qu2Atex39HKaPUfBtHxlgPwUAQkY/GZE6WoJVq7B1pHlPk/JOC4/8roBii3LjtLeDJ2VJ8C53nV/+WLUAE2Javlk75SsfmqoprlELsSnEDDeOl4MkvvvgoA/uA=
  - secure: RxdDmkcgtVMcgwIkd78PwlFXQkAB6BuiZrkw7NKwXyX4tdpZBrYy8vNxvDPMJaib6lukvoauJcWvNxWg3y/EDfwNDhAj9T6kQ0Oe607V8Vse4m8hJmGx64ObVLKmP7Fuh9ptBluqPLZwmpH5+7RpiIQNHW/6Ik2OH3Gsf5rxVJQP5VtsAIlCmSfkxAQpLkc9EwBTjuz8Z2X0xKPGGosclcqj/qfOHLmbb21d6gHmCvr3ezFI3XPwCAZX7e6ojKwh+F1XtJhLHuIBbSJOrVklX1ps45I7+XgeTAZisXjZyxj3+zElZ89qOmD/K03bbkN5cwu2KIZSve6ylcRuRmO7rh1hy2dXgHocr59Q5BfLmMR+Ef2/Wcg83nTdxmKUu94jIyuSDicd+kXLTyvBKSk/M+h+0uA4/j6YZ/ocrtOUsHiZLivfh0vs4J0Fn1slROvWSqaPOVcTyRV5MFN2FhsJnpDyeQP4bdhv79S3kkP0epqh5vXO2M+jtq9bfJCv5M3fyiX6fFt3cvZs566ab0SqPWBmD7L9MHYCuO2jV6Gpj6C9yv5NifSAIeo4zRpWMCK+7MpcnQWLI5tsY+0l898kJ2EGdawGm3Z/CTEHbtYNSm3APWlKMQvwK84lprEoI6ULATi6RVQUE5Z5OKTcCp8vi+E429a0jIQDyMWTisl0qgU=
